# .github/workflows/tagpr.yml
name: tagpr
on:
  push:
    branches: ["main"]

jobs:
  tagpr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
        uses: Songmu/tagpr@v1
      - name: Checkout released
        uses: actions/checkout@v4
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          ref: ${{ steps.tagpr.outputs.tag }}
      - name: Set up Go
        uses: actions/setup-go@v5
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
            go-version: "1.21"
      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v5
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          version: latest
          args: release
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.tagpr.outputs.tag != '' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: ${{ steps.tagpr.outputs.tag != '' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.tagpr.outputs.tag }}
